font_family Fira Code
font_size 10
remember_window_size no
tab_bar_edge top
tab_bar_style fade
active_tab_font_style bold
inactive_tab_font_style normal
map ctrl+shift+] next_tab
map ctrl+shift+[ previous_tab
map cmd+t new_tab
