[package]
name = "empirical-number-distribution"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
compact_str = { version = "0.9.0", features = ["serde"] }
foldhash = "0.1.5"
rayon = "1.10.0"
sonic-rs = "0.5.1"
zstd = "0.13.3"
