#include <stdint.h>
#include <stdbool.h>
#include <stdio.h>
#include <complex.h>
#include <string.h>
#include <stdlib.h>

#define nfibs 93
#define what int64_t
#define the fibs
#define fuck [
#define did nfibs
#define you ]
#define just =
#define fucking {
#define say 0
#define about ,
#define me 1
#define YOU ,
#define little 0
#define bitch }
#define i ;
#define ll void
#define have initf
#define YoU (
#define know )
#define I {
#define graduated for
#define top (
#define of int
#define my k
#define class =
#define in 2
#define tHe ;
#define navy k
#define seals <
#define and nfibs
#define ve k
#define been ++
#define involved )
#define In {
#define numerous fibs
#define secret [
#define raids k
#define on ]
#define al_quaeda =
#define anD fibs
#define i_ [
#define haVE k
#define over -
#define three 1
#define hundred ]
#define confirmed +
#define kills fibs
#define am k
#define trained -
#define gorilla ]
#define warfare ;
#define aNd }
#define I_ }
#define m bool
#define thE iusol
#define TOp [
#define sniper nfibs
#define IN ]
#define THE =
#define entire {
#define us 0
#define armed }
#define forces ;
#define yoU int
#define are bsectf
#define nothing (
#define to int64_t
#define Me n
#define but ,
#define JUsT int
#define another aa
#define target ,
#define i__ int
#define will b
#define wipe )
#define YOu {
#define The while
#define FuCK (
#define out aa
#define with <
#define precision b
#define THe )
#define likes {
#define which mid
#define has =
#define never (
#define BEEN aa
#define seen +
#define before b
#define ON )
#define this >>
#define earth 1
#define mark ;
#define My if
#define fuCkINg (
#define words fibs
#define yOu [
#define think mid
#define can <
#define get n
#define away )
#define With {
#define saying aa
#define that =
#define shit mid
#define TO +
#define ovEr ;
#define ThE }
#define internet else
#define Think {
#define again b
#define fucker =
#define as mid
#define we ;
#define speak }
#define aM return
#define contacting aa
#define MY ;
#define SecrEt }
#define network int
#define oF sumf
#define spies (
#define across int64_t
#define tHE trg
#define usa )
#define aND {
#define your int
#define ip pt
#define is =
#define being bsectf
#define traced (
#define right trg
#define now ,
#define so 0
#define yOU ,
#define better nfibs
#define prepare )
#define FOr ;
#define the_ if
#define storm (
#define maggot fibs
#define ThE_ [
#define STorm pt
#define THAT ]
#define wipes ==
#define ouT trg
#define pathetic {
#define LitTLe iusol
#define thing [
#define You pt
#define call ]
#define yOur =
#define life true
#define you_ ;
#define re return
#define FuCKINg 1
#define dead ;
#define kid }
#define I__ for
#define CAN (
#define be int
#define anywhere k
#define anytime =
#define And pt
#define i___ -
#define cAN 1
#define kill ;
#define You_ k
#define iN >
#define OvER 1
#define seven ;
#define hUndred k
#define ways --
#define AND )
#define tHat {
#define s if
#define jusT (
#define WitH iusol
#define mY [
#define bare k
#define hands ]
#define not )
#define only continue
#define AM ;
#define I___ iusol
#define extensively [
#define trAInEd k
#define unarmed =
#define combat true
#define bUT ;
#define i____ if
#define Have (
#define access sumf
#define tO (
#define eNtIRe -
#define arsenal fibs
#define Of [
#define THE_ k
#define united ]
#define states )
#define marine )
#define corps return
#define ANd 1
#define WILl iusol
#define use [
#define it k
#define To ]
#define its =
#define full false
#define extent ;
#define to_ }
#define WiPe return
#define YoUR 0
#define miserable ;
#define ass }
#define off long
#define tHE_ *
#define face f
#define OF (
#define tHe_ int64_t
#define continent trg
#define LIttle int
#define ShIT *
#define iF length
#define OnLY )
#define could if
#define hAvE (
#define known fibs
#define whAt [
#define unholy 2
#define retribution ]
#define YouR ==
#define clever )
#define comment initf
#define was (
#define aBout )
#define To_ ;
#define bring memset
#define down (
#define upon iusol
#define maybe 0
#define would nfibs
#define hAVE )
#define held ;
#define YOUR sumf
#define FUCkIng (
#define tongue trg
#define buT )
#define couldn *
#define t length
#define YoU_ =
#define didn 0
#define T ;
#define AnD for
#define NOw (
#define RE k
#define paying =
#define The_ 0
#define price ;
#define YOU_ k
#define goddamn <
#define idiot nfibs
#define wiLl k
#define shIT ++
#define fury )
#define all {
#define OVEr if
#define and_ iusol
#define wilL k
#define drown ]
#define in_ )
#define iT {
#define Re *
#define FuCkING length
#define DEad )
#define kiddo ++
#define WhAT ;
#define f___ }
#define DID int
#define yOU_ j
#define f___ing 0
#define type ;
#define AbOuT long
#define ME *
#define yOu_ out
#define lITTLe =
#define bitcH calloc
#define I____ (
#define Ll *
#define HAVe length
#define Know sizeof
#define gRADUaTED uint64_t
#define ToP )
#define of_ )
#define CLaSs for
#define at (
#define mit int
#define aNd_ k
#define i_____ =
#define Ve 0
#define bEEN ;
#define INVoLVED k
#define IN_ <
#define NUmeRouS nfibs
#define secreT ;
#define wITH ++
#define anonymous )
#define HAve (
#define oVer iusol
#define threE [
#define hUNdReD k
#define coNfIRMEd ]
#define ddoses )
#define Am out
#define trAined [
#define In_ j
#define online ]
#define trolling =
#define anD_ k
#define M j
#define thE_ ++
#define tOp ;
#define hacker }
#define iN_ }
#define THe_ return
#define ENTirE out
#define world ;
#define YOu_ }
#define aRe int
#define NOthinG main
#define mE )
#define BUt {
#define juSt initf
#define AnotHER (
#define virus )
#define host ;
#define WilL (
#define wIpE int
#define yoU_ k
#define F___ 0
#define oUt ;
#define wITh k
#define PReCiSiON <
#define the__ 100
#define LIKeS ;
#define oF_ k
#define WHICH ++
#define Has )
#define nevEr {
#define BeEN sumf
#define sEen (
#define befoRE 1
#define InTeRNET sumf
#define mArK (
#define my_ 2
#define f___Ing )
#define wORds ;
#define ThinK }
what the fuck did you just fucking say about me YOU little bitch i ll have YoU know I graduated top of my class in tHe navy seals and i ve been involved In numerous secret raids on al_quaeda anD i_ haVE over three hundred confirmed kills i_ am trained in gorilla warfare aNd I_ m thE TOp sniper IN THE entire us armed forces yoU are nothing to Me but JUsT another target i__ will wipe YOu The FuCK out with precision THe likes of which has never BEEN seen before ON this earth mark My fuCkINg words yOu think you can get away With saying that shit TO me ovEr ThE internet Think again fucker as we speak I_ aM contacting MY SecrEt network oF spies across tHE usa aND your ip is being traced right now so yOU better prepare FOr the_ storm maggot ThE_ STorm THAT wipes ouT THe pathetic LitTLe thing You call yOur life you_ re FuCKINg dead kid I__ CAN be anywhere anytime And i___ cAN kill You_ iN OvER seven hUndred ways AND tHat s jusT WitH mY bare hands not only AM I___ extensively trAInEd IN unarmed combat bUT i____ Have access tO tHE eNtIRe arsenal Of THE_ united states marine corps ANd i WILl use it To its full extent to_ WiPe YoUR miserable ass off tHE_ face OF tHe_ continent yOU LIttle ShIT iF OnLY YOu could hAvE known whAt unholy retribution YouR little clever comment was aBout To_ bring down upon yOU maybe YOU would hAVE held YOUR FUCkIng tongue buT you_ couldn t YoU_ didn T AnD NOw yoU RE paying The_ price YOU_ goddamn idiot i wiLl shIT fury all OVEr YoU and_ yOu wilL drown in_ iT YoU Re FuCkING DEad kiddo WhAT ThE f___ DID yOU_ just f___ing type AbOuT ME yOu_ lITTLe bitcH I____ Ll HAVe yOU Know I____ gRADUaTED ToP of_ MY CLaSs at mit aNd_ i_____ Ve bEEN INVoLVED IN_ NUmeRouS secreT raids wITH anonymous aND i____ HAve oVer threE hUNdReD coNfIRMEd ddoses I Am trAined In_ online trolling anD_ i M thE_ tOp hacker iN_ THe_ ENTirE world YOu_ aRe NOthinG tO mE BUt juSt AnotHER virus host I__ WilL wIpE yoU_ THE F___ oUt wITh PReCiSiON the__ LIKeS oF_ WHICH Has nevEr BeEN sEen befoRE ON tHe InTeRNET mArK my_ f___Ing wORds YOu_ ThinK
